repos:
  - repo: local
    hooks:
      - id: alejandra
        name: alejandra
        entry: alejandra
        language: system
        files: \.nix$
        pass_filenames: true
        
      # Validation hooks - skip with SKIP=nix-flake-check,nix-eval-check git commit
      - id: nix-flake-check
        name: Nix flake check (skip with SKIP=nix-flake-check)
        entry: bash -c 'if [[ $(git diff --cached --name-only | grep -E "\.(nix|lock)$") ]]; then nix flake check --no-write-lock-file; fi'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        
      - id: nix-eval-check
        name: Check nixos config evaluation (skip with SKIP=nix-eval-check)
        entry: bash -c 'if [[ $(git diff --cached --name-only | grep -E "\.(nix)$") ]]; then nix eval --no-write-lock-file --show-trace --expr "let flake = builtins.getFlake (toString ./.); in flake.lib.buildSystem \"test.headless.stable\"" >/dev/null; fi'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]